j-easy/easy-random

random-beans-java8/src/test/java/io/github/benas/randombeans/randomizers/java8/YearRandomizerTest.java, random-beans-java8/src/test/java/io/github/benas/randombeans/randomizers/java8/internal/DayRandomizerTest.java, random-beans-java8/src/test/java/io/github/benas/randombeans/randomizers/java8/internal/HourRandomizerTest.java, random-beans-java8/src/test/java/io/github/benas/randombeans/randomizers/java8/internal/MinuteRandomizerTest.java, random-beans-validation/src/test/java/io/github/benas/randombeans/validation/BeanValidationTest.java, random-beans/src/test/java/io/github/benas/randombeans/PriorityComparatorTest.java, random-beans/src/test/java/io/github/benas/randombeans/randomizers/DateRangeRandomizerTest.java, random-beans/src/test/java/io/github/benas/randombeans/randomizers/DateStringRandomizerTest.java
I found some test which can be simplified a bit.
=> slight simplification of some tests

random-beans/src/main/java/io/github/benas/randombeans/PopulatorImpl.java, random-beans/src/test/java/io/github/benas/randombeans/CollectionPopulationTest.java, random-beans/src/test/java/io/github/benas/randombeans/PopulatorImplTest.java, random-beans/src/test/java/io/github/benas/randombeans/beans/PrimitiveArrayBean.java
Here is a fix. I tried but couldn't find a cleaner way to handle it.
I won't be able to spend any time on side projects for the next few weeks.
I really like the cleanup of the collection population tests, by the way.
=> fix getRandomArray to handle primitives

pom.xml, random-beans/pom.xml, random-beans/src/main/java/io/github/benas/randombeans/util/FastClasspathScannerFacade.java, random-beans/src/main/java/io/github/benas/randombeans/util/ReflectionUtils.java
fast-classpath-scanner has no dependencies and seems to be better maintained
=> replace org.reflections with io.github.lukehutch.fast-classpath-scanner

random-beans/src/main/java/io/github/benas/randombeans/util/Constants.java, random-beans/src/main/java/io/github/benas/randombeans/util/DateUtils.java
change the constant reference date around which random dates will be generated from LocalDateTime to ZonedDateTime so the tests work independently local timezone
=> fixes #105:

pom.xml, random-beans-randomizers/src/test/java/io/github/benas/randombeans/randomizers/RandomizersTest.java
the 0.8 release supports many more locales, but it also uses different data-files, so some tests had to be changed
=> update to java-faker 0.8

random-beans/src/main/java/io/github/benas/randombeans/ArrayPopulator.java
Hi,
I have "solved" bounty found in source code. It is less verbose solution but it uses java.lang.reflect.Array#set method. I know that this is not the best solution (I am aware of reflection and some performance penalty of native methods) but it could be good enough ... so if you like it, merge it, or abandon it :)
Ivos
=> Use java.lang.reflect.Array.* for primitive array "generic" operations

pom.xml
objenesis 2.3 contains some bugfixes releated to android support: https://github.com/easymock/objenesis/commit/3938c80acc5b60cc4550f493fe4d0a882a367a36
=> Remove commons lang

pom.xml
"Performance enhancements for large classpaths with few match criteria."
=> update fast-classpath-scanner version to 1.9.21

pom.xml
It claims to be even faster now: https://github.com/lukehutch/fast-classpath-scanner/commit/deba683a9297021eaa8e707379a6a92f3d4bdfec
=> update fast-classpath-scanner version to 1.10.3

pom.xml, random-beans/src/main/java/io/github/benas/randombeans/util/FastClasspathScannerFacade.java
Not finished, I just want to test if the test failures I get locally also occur on travis ci.
=> update fast-classpath-scanner version to 1.90.8

random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java, random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java
=> #184 Reuse EnumRandomizer instances in EnhancedRandomImpl to ensure randomness.

random-beans-spring/src/main/java/io/github/benas/randombeans/spring/EnhancedRandomFactoryBean.java, random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomBuilder.java, random-beans/src/main/java/io/github/benas/randombeans/api/EnhancedRandomParameters.java, random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/InternalRandomizerRegistry.java, random-beans/src/main/java/io/github/benas/randombeans/randomizers/text/StringRandomizer.java, random-beans/src/main/java/io/github/benas/randombeans/util/Constants.java, random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java, random-beans/src/test/java/io/github/benas/randombeans/randomizers/text/StringRandomizerTest.java
=> add minStringLength parameter

random-beans/src/main/java/io/github/benas/randombeans/MapPopulator.java, random-beans/src/test/java/io/github/benas/randombeans/MapPopulatorTest.java
Null keys not supporter by TreeMap, ConcurrentHashMap, ConcurrentSkipListMap
=> Null keys not supporter by TreeMap, ConcurrentHashMap, ConcurrentSkipListMap

random-beans/src/main/java/io/github/benas/randombeans/FieldDefinition.java, random-beans/src/main/java/io/github/benas/randombeans/FieldDefinitionBuilder.java, random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/AbstractRandomizerRegistry.java, random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/CustomRandomizerRegistry.java, random-beans/src/main/java/io/github/benas/randombeans/randomizers/registry/ExclusionRandomizerRegistry.java, random-beans/src/test/java/io/github/benas/randombeans/CustomRandomizerTest.java, random-beans/src/test/java/io/github/benas/randombeans/FieldExclusionTest.java, random-beans/src/test/java/io/github/benas/randombeans/beans/Person.java
Add ability to exclude fields by field modifier
Add ability to register CustomRandomizer for field with specific field modifier
=> Add field modifier to FieldDefinition

random-beans/src/main/java/io/github/benas/randombeans/randomizers/text/StringRandomizer.java, random-beans/src/test/java/io/github/benas/randombeans/EnhancedRandomImplTest.java, random-beans/src/test/java/io/github/benas/randombeans/randomizers/text/StringRandomizerTest.java
=> fix StringRandomizer never returns Strings of maxStringLength

README.md, pom.xml, random-beans/src/main/java/io/github/benas/randombeans/randomizers/misc/EnumRandomizer.java, random-beans/src/test/java/io/github/benas/randombeans/randomizers/misc/EnumRandomizerTest.java
add random on subset of enumeration
=> add random on subset of enumeration

random-beans/src/main/java/io/github/benas/randombeans/EnhancedRandomImpl.java
This will allow consumers to incrementally process the object stream
=> refactor the objects stream to generate values lazily

random-beans-validation/src/main/java/io/github/benas/randombeans/validation/FutureAnnotationHandler.java, random-beans-validation/src/main/java/io/github/benas/randombeans/validation/PastAnnotationHandler.java, random-beans-validation/src/test/java/io/github/benas/randombeans/validation/BeanValidationAnnotatedBean.java, random-beans-validation/src/test/java/io/github/benas/randombeans/validation/BeanValidationTest.java
Another quick (and dirty) way to implement this feature.
=> Past/Future annotation cannot be applied to Java 8 date types #328

README.md, easy-random-bean-validation/src/test/java/org/jeasy/random/validation/BeanValidationAnnotatedBean.java, easy-random-bean-validation/src/test/java/org/jeasy/random/validation/BeanValidationMethodAnnotatedBean.java, easy-random-core/src/main/java/org/jeasy/random/randomizers/range/InstantRangeRandomizer.java, easy-random-core/src/main/java/org/jeasy/random/randomizers/registry/TimeRandomizerRegistry.java, easy-random-core/src/test/java/org/jeasy/random/randomizers/range/InstantRangeRandomizerTest.java
https://github.com/j-easy/easy-random/issues/382
=> Add instant range randomizer

easy-random-core/pom.xml, easy-random-core/src/main/java/org/jeasy/random/util/ReflectionUtils.java, easy-random-core/src/test/java/org/jeasy/random/EasyRandomTest.java, easy-random-core/src/test/java/org/jeasy/random/beans/FluentSetterBean.java, easy-random-core/src/test/java/org/jeasy/random/util/ReflectionUtilsTest.java, pom.xml
=> Feature use fluent setters when populating bean

easy-random-randomizers/src/test/java/org/jeasy/random/randomizers/PasswordRandomizerTest.java
Thank you for taking time to contribute this pull request :smile:
You have probably already checked the following points, but as a reminder, please ensure that:
* your branch is rebased on the latest version of the master branch
* all tests pass
* code is formatted with IntelliJ Idea default settings (if you use another IDE, never mind, ignore this point)
You may add the reference of the issue in your commit message.
Don't hesitate to add your name to the contributors list in the `README.md` file.
Many thanks upfront!
=> improve test

.github/workflows/build.yml
This will notably remove download progress in logs
=> CI: run maven in batch mode

easy-random-core/src/main/java/org/jeasy/random/randomizers/range/InstantRangeRandomizer.java, easy-random-core/src/main/java/org/jeasy/random/randomizers/registry/InternalRandomizerRegistry.java, easy-random-core/src/main/java/org/jeasy/random/util/ConversionUtils.java, easy-random-core/src/test/java/org/jeasy/random/parameters/DateTimeRangeParameterTests.java
=> Fix for LocalDate.MIN and LocalDate.MAX range value exceptions #483
